language:
  - cpp

compiler:
  - gcc

script:
  - cmake -DSFML_ROOT=SFML-2.1 . && make && sudo make install

before_script:
  - wget http://www.sfml-dev.org/download/sfml/2.1/SFML-2.1-linux-gcc-64bits.tar.bz2
  - tar -xjf SFML-2.1-linux-gcc-64bits.tar.bz2

after_scrip:
  - ls -l /usr/local/lib

branches:
  only:
    - master

notifications:
  recipients:
    - lucas.soltic@orange.fr
  email:
    on_success: always
    on_failure: always
